# Generated by Django 3.2.9 on 2022-01-12 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(choices=[('Boulder', 'Boulder Badge'), ('Cascade', 'Cascade Badge'), ('Thunder', 'Thunder Badge'), ('Rainbow', 'Rainbow Badge'), ('Soul', 'Soul Badge'), ('Marsh', 'Marsh Badge'), ('Volcano', 'Volcano Badge'), ('Earth', 'Earth Badge'), ('Zephyr', 'Zephyr Badge'), ('Hive', 'Hive Badge'), ('Plain', 'Plain Badge'), ('Fog', 'Fog Badge'), ('Storm', 'Storm Badge'), ('Mineral', 'Mineral Badge'), ('Glacier', 'Glacier Badge'), ('Rising', 'Rising Badge'), ('Stone', 'Stone Badge'), ('Knuckle', 'Knuckle Badge'), ('Dynamo', 'Dynamo Badge'), ('Heat', 'Heat Badge'), ('Balance', 'Balance Badge'), ('Feather', 'Feather Badge'), ('Mind', 'Mind Badge'), ('Rain', 'Rain Badge')], default='Boulder', max_length=25)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pokemon')),
            ],
        ),
    ]
